all/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='index')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views

app_name = 'myappurl'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
    path('track/', views.track, name = 'track'),
    path('result/', views.result, name = 'result'),
    path('loc_two/', views.details_two, name = 'loc_two')

]

myapp/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify


class cons(models.Model):
    caption = models.CharField(max_length=200)
    true = models.CharField(max_length=200)
    trac_one = models.CharField(max_length=200)
    def __str__(self):
        return self.caption


# comment

class comment(models.Model):
    name = models.CharField(max_length=200)
    comments = models.CharField(max_length=1000)
    def __str__(self):
        return self.name

# location
class location(models.Model):
    status = models.CharField(max_length=200)
    previous_location = models.CharField(max_length=200)
    current_location = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    delivery_date = models.CharField(max_length=200)
    map = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.status


class location_two(models.Model):
    status = models.CharField(max_length=200)
    previous_location = models.CharField(max_length=200)
    current_location = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    delivery_date = models.CharField(max_length=200)
    map = models.CharField(max_length=1000)
    
    def __str__(self):
        return self.status

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponse

# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.decorators import login_required
from .models import cons
from .models import comment
from .models import location
from .models import location_two



# Create your views here.

def index(request):


    com = comment.objects.all()
    
    return render(request, 'index.html', {'com':com})

def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def track(request):


    # form = request.POST.get("identity")
    # fas = request.POST.get("true_value")
    # if request.method == 'POST':

    #     form = request.POST.get("identity")
    #     fas = request.POST.get("true_value")
    # elif fas == form:
    #      return redirect("index:about")

    # else:
    #     return redirect("index:contact")
       
    # else:
    #     return redirect("index:contact")
    # nice = ''
    # cool = ''
    
    if request.method == 'POST':
        nice = request.POST.get('identity')
        t_one = request.POST.get('identity_one')
        cool = request.POST.get('true_value')
        

        data = cons(caption=nice, true=t_one, trac_one=cool)
        data.save()

    
        if nice == cool:
            return redirect("index:result")
        
        elif t_one == cool:
            return redirect("index:loc_two")
        
            
        
        else:
            messages.success(request, f'Location not available, try again')
            return redirect("index:track")



    wis = cons.objects.all()

      

    

    return render(request, 'track.html', {'wis':wis})


def result(request):
    loc = location.objects.all()

    

    return render(request, 'result.html', {'loc':loc})

# location two

def details_two(request):
    loc_two = location_two.objects.all()

    return render(request, 'id_one.html', {'loc_two':loc_two})

myapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="full">
    <div class="section-contain">
        <div class="content_section">
            <div class="title">
                <h3>About Us</h3>
            </div>
            <div class="content">
                <h3>
                    OUR STORY
                </h3>

                <P>
                    We take pride in being regarded as one of the most reliable and affordable logistic and warehousing service providers in the country. As a third party logistic service provider, we excel at a range of logistic services, which includes trucking services, warehousing services, logistic services, and a range of other ancillary services. We have years of experience in the business of logistics, warehousing, distribution, trucking and supply chain management services, and aim to provide our clients with convenience, reliability and affordability through our premium logistic services. <br>
                    </P>
                    <p>

                    Our team of experts at all levels of our services have years of experience backing them, which adds the credibility of an expert workforce. This also helps us in cutting down response time, and providing punctual delivery and services at all times, whether it is trucking service or warehousing services. Our goal is to make a positive difference in your business through our services, and build long term relationship with you. Our commitment to our clients can be seen by the amount of emphasis we lay on team work, customer support services and making technological upgrades in our logistic process and equipment from time to time. <br>

                    
                                    </P>
                <div class="button">
                    <a href="">WE ARE RELIABLE </a>
                </div>
            </div>
            <div class="ssocal">

            </div>
        </div>
        <div class="image-section">
            <img src="{% static './img/aero1.avif'%}" alt="">
        </div>
    </div>
</div>

{% endblock content %}

myapp/templates/base.html
{% load static %}
{% include 'header.html' %}
{% block content %}
{% endblock content %}
{% include 'footer.html' %}

myapp/templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './footer.css'%}">
    <title>Document</title>
</head>
<body>
    <footer>
        <div class="waves">
            <div class="wave" id="wave1"></div>
            <div class="wave" id="wave2"></div>
            <div class="wave" id="wave3"></div>
            <div class="wave" id="wave4"></div>
        </div>
        <ul class="social_icon">
            <li><a href=""><ion-icon name="logo-facebook"></ion-icon></a></li>
            <li><a href=""><ion-icon name="logo-twitter"></ion-icon></a></li>
            <li><a href=""><ion-icon name="logo-whatsapp"></ion-icon></a></li>
            <li><a href=""><ion-icon name="logo-instagram"></ion-icon></a></li>
        </ul>
        <ul class="menu">

            <li><a href="{% url 'myappurl:index' %}">Home</a></li>
            <li><a href="{% url 'myappurl:about' %}">About</a></li>
            <li><a href="{% url 'myappurl:track' %}">Track</a></li>
            <li><a href="{% url 'myappurl:contact' %}">Contact</a></li>
           
            
        </ul>
        <p>
            
            © 2022 Cargo Shipments. All rights reserved.
        </p>
    </footer>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    
</body>
</html>

myapp/templates/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/img/Graphic1.png" type="image/x-icon">
    <link rel="stylesheet" href="{% static './js/bootstrap.min.js'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="{% static './style.css'%}">
    <link rel="stylesheet" href="{% static './main.css'%}">
    <title>Cargo Shipments | International </title>
    
</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="menu">
                <h3 class="logo">  CARGO <span> Shipment</span></h3>
                <div class="hamburger-menu">
                    <div class="bar"></div>
                </div>
            </div>
        </div>
        <div class="main-container">
            <div class="main">
                <header>
                    <div class="overlay">
                        <div class="inner">
                            <h2 class="title">Wecome to Cargo Shipments</h2>
                            <p>
                                The most reliable shipping company around the Globe
                            </p>
                            <a href="{% url 'myappurl:track' %}" class="btn">Track ... </a>
                        </div>
                    </div>
                </header>
            </div>

            <div class="shadow one"></div>
            <div class="shadow two"></div>
        </div>

        <div class="links">
            <ul>
                <li>
                    <a href="{% url 'myappurl:index' %}" style="--i: 0.05s">Home</a>
                </li>
                <li>
                    <a href="{% url 'myappurl:about' %}"style="--i: 0.1s">About</a>
                </li>
                <li>
                    <a href="{% url 'myappurl:contact' %}"style="--i: 0.15s">Contact</a>
                </li>
                
                <li>
                    <a href="{% url 'myappurl:track' %}"style="--i: 0.25s">Track</a>
                </li>
                
            </ul>
        </div>
    </div>
    <script src="{% static './js/script.js'%}"></script>
    <script src="{% static './js/track.js'%}"></script>
</body>
</html>

myapp/templates/id_one.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/img/Graphic1.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static './main.css'%}"> 
    <title>Track</title>
</head>
<body>
    <!-- bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- <a class="navbar-brand" href="{% url 'myappurl:index' %}">CARGO SHIPMENTS</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myappurl:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:about' %}">About <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:track' %}">Track <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:contact' %}">Contact <span class="sr-only">(current)</span></a>
              </li>
            
              
             
            </li>
           
          </ul>
          
        </div>
      </nav>
    <div class="result">
        <div class="location">
            <div class="locate">
                <h3>PRODUCT DETAILS</h3>
                {% for a in loc_two %}
                <!-- <i>STATUS: </i> <b>{{a.status}}</b> <br>
                <i>Previous Location: </i> <b>{{a.previous_location}}</b> <br>
                <i>Current Location:  </i> <b>{{a.current_location}}</b> <br>
                <i>Address:   </i><b>{{a.address}}</b><br>
                <i>City:  </i> <b>{{a.city}}</b><br>
                <i>Destination:  </i> <b>{{a.destination}}</b><br>
                <i>Delivery Date:  </i> <b>{{a.delivery_date}}</b><br> -->

                  <table class="tab">
                    <tr> 
                      <td>Status :</td>
                      <td><b>{{a.status}}</b></td>

                    </tr>
                    <tr> 
                      <td>Previous Location:</td>
                      <td><b>{{a.previous_location}}</b></td>

                    </tr>
                    <tr> 
                      <td>Current Location:</td>
                      <td><b>{{a.current_location}}</b></td>

                    </tr>
                    <tr> 
                      <td>Receiver's Address:</td>
                      <td><b>{{a.address}}</b></td>

                    </tr>
                    <tr> 
                      <td>City:</td>
                      <td><b>{{a.city}}</b></td>

                    </tr>
                    <tr> 
                      <td>Destination:</td>
                      <td><b>{{a.destination}}</b></td>

                    </tr>
                    <tr> 
                      <td>Deliver Date</td>
                      <td><b>{{a.delivery_date}}</b></td>

                    </tr>

                  </table>

                <p class="id_map"> <iframe src="{{a.map}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></a> </p>
                {% endfor %}


            </div>
        </div>
    </div>

    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

{% include 'footer.html' %}

myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="welcome">
    <div class="note">
        <h1> <span> Welcome To</span><b> Cargo Shipments</b> </h1>
        <p> Our warehousing services are known nationwide to be one of the most reliable, safe and affordable, because we take pride in delivering 
            the best of warehousing services, at the most reasonable prices. Our own warehouses, 
            as well as our partner’s warehouses are located at strategic locations to ensure that there is no additional cost. <br>
            Our customer services are superb, got a question for us? Don't forget to contact us as we are available for you 24/7 <br>
            <b class="excel">Excellence is our Watchword!!!</b>
        </p>
    </div>
</div>

<div class="section">
    <div class="inner-section">
        <h2 class="special">CLIENT SATISFACTION IS OUR PRIMARY <br> FOCUS</h2>
        <P><b> We Deliver with the Speed of Light</b></P>
    </div>

    <button><a href="{% url 'myappurl:track' %}">Track  </a></button>
</div>

<!-- Special -->
<div class="our_special">
    <h1> <b> Our </b> Services</h1>
    <div class="css_columns">

        
            <p class="service"> <ion-icon name="storefront-outline"></ion-icon> <b>Packaging And Storage</b> <br>
                We package and store your goods

            </p>

            <p class="service"><ion-icon name="home-sharp"></ion-icon> <b>Warehousing</b> <br>
                We have top notch security and loads of space. Store your stuff in our ware house.​

            </p>

            <p class="service"> <ion-icon name="car-sport-sharp"></ion-icon></ion-icon><b>Ground Transport</b> <br>
                Transport your things in our super fast moving van

            </p>

            <p class="service"> <ion-icon name="earth-outline"></ion-icon><b>World Wide Transport</b> <br>
                We can transport your things anywhere in the world

            </p>

            
            

            <p class="service"> <ion-icon name="home-sharp"></ion-icon> <b>Cargo</b> <br>
                Let us transport your things from point A to B fast and secure

            </p>
            

            <p class="col_img">
                <img src="{% static './img/ship4.avif'%}" alt="">
                
            </p>
            
        </div>

        

    </div>



    <!-- comments -->

    <div class="comment">
        <h2> What Our Client Say </h2>
        <div class="words">
            {% for b in com %}
            <p> <h3>{{b.name}} </h3>
                <B>" </B> 
                <i> {{b.comments}}</i> 
                <B>"</B>
                

            </p>

            {% endfor %}

            
        

        </div>
    </div>

   <!-- gallery -->

   <div class="gallary">
       <h2><b class="gg"> G a </b> l l e r y </h2>
   <div class="gala">
    <p class="col_img">
        <img src="{% static './img/first.jpg'%}" alt="" style="height: 400px;">
        
    </p>
    <p class="col_img">
        <img src="{% static './img/aero2.jpg'%}" alt="" style="height: 400px;">
        
    </p>

    <p class="col_img">
        <img src="{% static './img/truck.jpeg'%}" alt="" style="height: 400px;">
        
    </p>
   </div>
</div>


<!-- counting numbers -->
<div class="achive">
    <h2><b> Our </b>  Achievements </h2>
<div class="wrapper">

    <div class="cone">
        <span class="num" data-val="1500">213</span>
        <span class="text">Awards</span>
    </div>

    <div class="cone">
        <span class="num" data-val="2000">232</span>
        <span class="text">Offices Worldwide</span>
    </div>

    <div class="cone">
        <span class="num" data-val="130">124</span>
        <span class="text">Country Covered</span>
    </div>

    <div class="cone">
        <span class="num" data-val="1200">205</span>
        <span class="text">Hardworking People</span>
    </div>

</div>

    <!-- <div class="cone">
        <span class="num" data-val="400">000</span>
        <span class="text">Meals Delivered</span>
    </div>

    <div class="cone">
        <span class="num" data-val="400">000</span>
        <span class="text">Meals Delivered</span>
    </div> -->

</div>




<!-- <div class="card">
    <div class="card__inner">
        <div class="card__face card__face--front">
            <h2>Developer Card</h2>
        </div>
        <div class="card__face card__face--back">
            <div class="card__content">
                <div class="card__header">
                    <img src="{% static './img/air.jpg'%}" alt="" class="pp">
                    <h2>Tyler Pottis</h2>
                </div>
                <div class="card__body">
                    <h3>JavaScript Wizard</h3>
                    <p>
                        "This is the fastest delivery company I have known,
                        I will recommend it any time. Never dissapointing and theier 
                        customer relation is superb"
                    </p>
                </div>
            </div>
        </div>
    </div>
</div> -->


<div class="contact-us">
    <h2><b> Contact</b> Us </h2>
    <div class="contact-content">
        <p> 
            <ion-icon name="location-outline"></ion-icon>
            <h3>Address</h3>

            125, Central Square, <br>
            New York, NY 286

        </p>
        <p>
            <ion-icon name="call-outline"></ion-icon>
            <h3>Call Us</h3>

            +447-7231-72932

        </p>

        <p> 
            <ion-icon name="mail-outline"></ion-icon>
            <h3>E-Mail</h3>

            support@cargoshipments.com

        </p>
        <p>
            <ion-icon name="time-outline"></ion-icon>
            <h3>Working Hours</h3>
            Mon-Fri: 10AM-5PM <br>
                Sat-Sun: 10AM-1PM

        </p>
    </div>
    </div>





<script src="{% static './js/card.js'%}"></script>
<script src="{% static './js/count.js'%}"></script>

{% endblock content %}

myapp/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/img/Graphic1.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static './main.css'%}"> 
    <title>Track</title>
</head>
<body>
    <!-- bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!-- <a class="navbar-brand" href="{% url 'myappurl:index' %}">CARGO SHIPMENTS</a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myappurl:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:about' %}">About <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:track' %}">Track <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myappurl:contact' %}">Contact <span class="sr-only">(current)</span></a>
              </li>
            
              
             
            </li>
           
          </ul>
          
        </div>
      </nav>
    <div class="result">
        <div class="location">
            <div class="locate">
                <h3>PRODUCT DETAILS</h3>
                {% for a in loc %}
                <!-- <i>STATUS: </i> <b>{{a.status}}</b> <br>
                <i>Previous Location: </i> <b>{{a.previous_location}}</b> <br>
                <i>Current Location:  </i> <b>{{a.current_location}}</b> <br>
                <i>Address:   </i><b>{{a.address}}</b><br>
                <i>City:  </i> <b>{{a.city}}</b><br>
                <i>Destination:  </i> <b>{{a.destination}}</b><br>
                <i>Delivery Date:  </i> <b>{{a.delivery_date}}</b><br> -->

                  <table class="tab">
                    <tr> 
                      <td>Status :</td>
                      <td><b>{{a.status}}</b></td>

                    </tr>
                    <tr> 
                      <td>Previous Location:</td>
                      <td><b>{{a.previous_location}}</b></td>

                    </tr>
                    <tr> 
                      <td>Current Location:</td>
                      <td><b>{{a.current_location}}</b></td>

                    </tr>
                    <tr> 
                      <td>Receiver's Address:</td>
                      <td><b>{{a.address}}</b></td>

                    </tr>
                    <tr> 
                      <td>City:</td>
                      <td><b>{{a.city}}</b></td>

                    </tr>
                    <tr> 
                      <td>Destination:</td>
                      <td><b>{{a.destination}}</b></td>

                    </tr>
                    <tr> 
                      <td>Deliver Date</td>
                      <td><b>{{a.delivery_date}}</b></td>

                    </tr>

                  </table>

                <p class="id_map"> <iframe src="{{a.map}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></a> </p>
                {% endfor %}


            </div>
        </div>
    </div>

    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

{% include 'footer.html' %}

myapp/templates/track.html
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/img/Graphic1.png" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static './main.css'%}"> 
    <title>Cargo Shipments International</title>
</head>
<body>
    <!-- bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- <a class="navbar-brand" href="{% url 'myappurl:index' %}">CARGO SHIPMENTS</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myappurl:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'myappurl:about' %}">About <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myappurl:track' %}">Track <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'myappurl:contact' %}">Contact <span class="sr-only">(current)</span></a>
            </li>
          
            
           
          </li>
         
        </ul>
        
      </div>
    </nav>

<div class="track">
    <div class="track-content">
        <h2>Track <ion-icon name="analytics-sharp"></ion-icon> </h2>
        <div class="div">
            <h3>Enter Consignment Number</h3>
            <form method="POST" class="track-inner">

                {% csrf_token %}
        
                {{ form|crispy }}

                {% for w in wis %}
                <input class="ident" type="text" id="number" placeholder="" name="identity" value="{{w.caption}}" > 
                <input class="ident" type="text" id="number" placeholder="" name="identity_one" value="{{w.true}}" > 

                {% endfor %}
               
                
                <input class="true" type="text" id="realNumber" placeholder="Enter Id Number" name="true_value" value="" > 
                
               
                <button id="demo" onclick="getValue()" type="submit"> Track </button>
            </form>
            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
        {% endfor %}
        {% endif %}
        </div>

    </div>
</div>
</body>


<script src="{% static './js/track.js'%}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

{% endblock content %}

{% include 'footer.html' %}